name: Compare current data

on:
  schedule:
    - cron:  '14 2 * * *'
  workflow_dispatch: {}

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: |-
        sudo apt-get install jq moreutils
        npm install -g wikibase-cli
        curl -L https://github.com/jqnatividad/qsv/releases/download/0.20.0/qsv-0.20.0-x86_64-unknown-linux-gnu.zip -o /tmp/qsv.zip
        sudo unzip -j -d /usr/local/bin /tmp/qsv.zip
    - name: Install ruby dependencies
      run: bundle install
    - name: Scrape official site (mirrored earlier)
      run: bundle exec ruby bin/scraper/official.rb | ifne tee data/official.csv
    - name: Get current wikidata list
      run: wd sparql -f csv bin/scraper/wikidata.js | sed -e 's/T00:00:00Z//g' | qsv dedup -s psid | ifne tee data/wikidata.csv
    - name: Generate diff
      run: bundle exec ruby bin/diff.rb | tee data/diff.csv
    - name: Scrape list of governors
      run: bundle exec ruby bin/scraper/governors-wikipedia.rb | ifne tee data/governors-wikipedia.csv
    - name: Generate governors diff
      run: bundle exec ruby bin/diff-governors.rb | ifne tee data/diff-governors.csv
    - name: Create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Automated update
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: data-update
        delete-branch: true
        title: 'Current member list'
        assignees: tmtmtmtm
        reviewers: tmtmtmtm
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
